package pe.edu.unsch.entities;
// Generated 07/07/2018 05:44:08 PM by Hibernate Tools 5.2.3.Final

import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Categoria generated by hbm2java
 */
@Entity
@Table(name = "categoria", catalog = "artesaniashop")
public class Categoria implements java.io.Serializable {

	private int idcategoria;
	private String nombre;
	private String estado;
	private String parentid;
	private List<Categoria> categories;

	public Categoria() {
	}

	public Categoria(int idcategoria) {
		this.idcategoria = idcategoria;
	}

	public Categoria(int idcategoria, String nombre, String estado, String parentid) {
		this.idcategoria = idcategoria;
		this.nombre = nombre;
		this.estado = estado;
		this.parentid = parentid;
	}

	@Id

	@Column(name = "idcategoria", unique = true, nullable = false)
	public int getIdcategoria() {
		return this.idcategoria;
	}

	public void setIdcategoria(int idcategoria) {
		this.idcategoria = idcategoria;
	}

	@Column(name = "nombre", length = 45)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "estado", length = 11)
	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	@Column(name = "parentid", length = 11)
	public String getParentid() {
		return this.parentid;
	}

	public void setParentid(String parentid) {
		this.parentid = parentid;
	}

	@OneToMany
	@JoinColumn(name = "parentid", referencedColumnName = "idcategoria")
	public List<Categoria> getCategories() {
		return categories;
	}

	public void setCategories(List<Categoria> categories) {
		this.categories = categories;
	}
}
