package pe.edu.unsch.entities;
// Generated 11-jul-2018 0:23:44 by Hibernate Tools 5.2.3.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Color generated by hbm2java
 */
@Entity
@Table(name = "color", catalog = "artesaniashop")
public class Color implements java.io.Serializable {

	private int idcolor;
	private String nombre;
	private Set<Producto> productos = new HashSet<Producto>(0);

	public Color() {
	}

	public Color(int idcolor) {
		this.idcolor = idcolor;
	}

	public Color(int idcolor, String nombre, Set<Producto> productos) {
		this.idcolor = idcolor;
		this.nombre = nombre;
		this.productos = productos;
	}

	@Id

	@Column(name = "idcolor", unique = true, nullable = false)
	public int getIdcolor() {
		return this.idcolor;
	}

	public void setIdcolor(int idcolor) {
		this.idcolor = idcolor;
	}

	@Column(name = "nombre", length = 100)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "color")
	public Set<Producto> getProductos() {
		return this.productos;
	}

	public void setProductos(Set<Producto> productos) {
		this.productos = productos;
	}

}
