package pe.edu.unsch.entities;
// Generated 25/07/2018 02:02:51 AM by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Detallecompra generated by hbm2java
 */
@Entity
@Table(name = "detallecompra", catalog = "artesaniashop")
public class Detallecompra implements java.io.Serializable {

	private String iddetallecompra;
	private Compra compra;
	private Producto producto;
	private Integer precio;
	private String cantidad;

	public Detallecompra() {
	}

	public Detallecompra(String iddetallecompra, Compra compra, Producto producto) {
		this.iddetallecompra = iddetallecompra;
		this.compra = compra;
		this.producto = producto;
	}

	public Detallecompra(String iddetallecompra, Compra compra, Producto producto, Integer precio, String cantidad) {
		this.iddetallecompra = iddetallecompra;
		this.compra = compra;
		this.producto = producto;
		this.precio = precio;
		this.cantidad = cantidad;
	}

	@Id

	@Column(name = "iddetallecompra", unique = true, nullable = false, length = 45)
	public String getIddetallecompra() {
		return this.iddetallecompra;
	}

	public void setIddetallecompra(String iddetallecompra) {
		this.iddetallecompra = iddetallecompra;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idcompra", nullable = false)
	public Compra getCompra() {
		return this.compra;
	}

	public void setCompra(Compra compra) {
		this.compra = compra;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idproducto", nullable = false)
	public Producto getProducto() {
		return this.producto;
	}

	public void setProducto(Producto producto) {
		this.producto = producto;
	}

	@Column(name = "precio")
	public Integer getPrecio() {
		return this.precio;
	}

	public void setPrecio(Integer precio) {
		this.precio = precio;
	}

	@Column(name = "cantidad", length = 45)
	public String getCantidad() {
		return this.cantidad;
	}

	public void setCantidad(String cantidad) {
		this.cantidad = cantidad;
	}

}
