package pe.edu.unsch.entities;
// Generated 11-jul-2018 0:23:44 by Hibernate Tools 5.2.3.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Marca generated by hbm2java
 */
@Entity
@Table(name = "marca", catalog = "artesaniashop")
public class Marca implements java.io.Serializable {

	private int idmarca;
	private String nombre;
	private Set<Producto> productos = new HashSet<Producto>(0);

	public Marca() {
	}

	public Marca(int idmarca) {
		this.idmarca = idmarca;
	}

	public Marca(int idmarca, String nombre, Set<Producto> productos) {
		this.idmarca = idmarca;
		this.nombre = nombre;
		this.productos = productos;
	}

	@Id

	@Column(name = "idmarca", unique = true, nullable = false)
	public int getIdmarca() {
		return this.idmarca;
	}

	public void setIdmarca(int idmarca) {
		this.idmarca = idmarca;
	}

	@Column(name = "nombre", length = 100)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "marca")
	public Set<Producto> getProductos() {
		return this.productos;
	}

	public void setProductos(Set<Producto> productos) {
		this.productos = productos;
	}

}
