package pe.edu.unsch.entities;
// Generated 25/07/2018 02:02:51 AM by Hibernate Tools 5.2.3.Final

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Producto generated by hbm2java
 */
@Entity
@Table(name = "producto", catalog = "artesaniashop")
public class Producto implements java.io.Serializable {

	private int idproducto;
	private Categoria categoria;
	private Color color;
	private Marca marca;
	private String nombre;
	private BigDecimal precio;
	private Integer cantidad;
	private String descrition;
	private String urlimg;
	private Byte caracteristica;
	private Set<Detallecompra> detallecompras = new HashSet<Detallecompra>(0);

	public Producto() {
	}

	public Producto(int idproducto, Categoria categoria, Color color, Marca marca) {
		this.idproducto = idproducto;
		this.categoria = categoria;
		this.color = color;
		this.marca = marca;
	}

	public Producto(int idproducto, Categoria categoria, Color color, Marca marca, String nombre, BigDecimal precio,
			Integer cantidad, String descrition, String urlimg, Byte caracteristica,
			Set<Detallecompra> detallecompras) {
		this.idproducto = idproducto;
		this.categoria = categoria;
		this.color = color;
		this.marca = marca;
		this.nombre = nombre;
		this.precio = precio;
		this.cantidad = cantidad;
		this.descrition = descrition;
		this.urlimg = urlimg;
		this.caracteristica = caracteristica;
		this.detallecompras = detallecompras;
	}

	@Id

	@Column(name = "idproducto", unique = true, nullable = false)
	public int getIdproducto() {
		return this.idproducto;
	}

	public void setIdproducto(int idproducto) {
		this.idproducto = idproducto;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idcategoria", nullable = false)
	public Categoria getCategoria() {
		return this.categoria;
	}

	public void setCategoria(Categoria categoria) {
		this.categoria = categoria;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idcolor", nullable = false)
	public Color getColor() {
		return this.color;
	}

	public void setColor(Color color) {
		this.color = color;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idmarca", nullable = false)
	public Marca getMarca() {
		return this.marca;
	}

	public void setMarca(Marca marca) {
		this.marca = marca;
	}

	@Column(name = "nombre", length = 200)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "precio", precision = 18)
	public BigDecimal getPrecio() {
		return this.precio;
	}

	public void setPrecio(BigDecimal precio) {
		this.precio = precio;
	}

	@Column(name = "cantidad")
	public Integer getCantidad() {
		return this.cantidad;
	}

	public void setCantidad(Integer cantidad) {
		this.cantidad = cantidad;
	}

	@Column(name = "descrition", length = 500)
	public String getDescrition() {
		return this.descrition;
	}

	public void setDescrition(String descrition) {
		this.descrition = descrition;
	}

	@Column(name = "urlimg", length = 100)
	public String getUrlimg() {
		return this.urlimg;
	}

	public void setUrlimg(String urlimg) {
		this.urlimg = urlimg;
	}

	@Column(name = "caracteristica")
	public Byte getCaracteristica() {
		return this.caracteristica;
	}

	public void setCaracteristica(Byte caracteristica) {
		this.caracteristica = caracteristica;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "producto")
	public Set<Detallecompra> getDetallecompras() {
		return this.detallecompras;
	}

	public void setDetallecompras(Set<Detallecompra> detallecompras) {
		this.detallecompras = detallecompras;
	}

}
